name: plant3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pytorch=2.0.1
  - torchvision
  - pytorch-cuda=11.8
  - cudatoolkit=11.8

  - pip:
      - numpy<2.0
      - plyfile
      - tqdm
      - opencv-python
      - matplotlib
      - Pillow
      - scipy
      - open3d
      - lpips
      - scikit-image
      - gsplat
    